#!/bin/bash
pwd
[Dpwd ~/alx-system_engineering-devops/0x00-shell_basics
pwd~/alx-system_engineering-devops/0x00-shell_basics

pwdrm
rm 



clear
\
















[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[A[Aclear
